// =========================================================
// PAGE: RAMADAN
// =========================================================
function pgRamadan(){
  if(!S.plan)return noProfCard();
  const tCal=S.plan.tCal;const splits={iftar:Math.round(tCal*0.4),snack:Math.round(tCal*0.15),suhoor:Math.round(tCal*0.45)};
  const p=el('div',{class:'page'});p.appendChild(el('div',{style:{marginBottom:'13px'}},el('span',{class:'badge bdg-yl',style:{marginBottom:'7px',display:'inline-flex'}},'🌙 RAMADAN'),el('h1',{class:'h1'},__('ramadan'))));
  const tc=el('div',{class:'card card-yl',style:{padding:'14px 15px',marginBottom:'13px'}});const tr=el('div',{class:'fb'});const ti=el('div',null);ti.appendChild(el('div',{style:{fontSize:'13px',fontWeight:'700',marginBottom:'3px'}},'🌙 Ramadan Mode'));ti.appendChild(el('div',{style:{fontSize:'12px',color:'var(--tx2)'}},'Activate to optimize your nutrition for fasting.'));tr.appendChild(ti);tr.appendChild(mkSw(S.ramadan,v=>{S.ramadan=v;saveS();checkAch();render();},'#f59e0b'));tc.appendChild(tr);p.appendChild(tc);
  const sc=el('div',{class:'card'});sc.appendChild(el('div',{class:'slbl'},'Daily Calorie Distribution'));sc.appendChild(el('div',{style:{fontSize:'28px',fontWeight:'900',textAlign:'center',color:'var(--yl2)',marginBottom:'11px'}},fmt(tCal)+' kcal'));
  [[__('iftar'),'🌙','#fbbf24',splits.iftar,40,'Dates + water → Harira → Chicken Tagine + salad'],[__('snack_m'),'🫖','#a78bfa',splits.snack,15,'Mint tea + Baghrir with honey'],[__('suhoor'),'🌅','#34d399',splits.suhoor,45,'Oatmeal + 2 eggs + Khobz + Leben']].forEach(([l,ic,c,v,pct,tip])=>{
    const row=el('div',{style:{padding:'11px 13px',borderRadius:'11px',background:c+'12',border:'1px solid '+c+'38',marginBottom:'9px'}});
    row.appendChild(el('div',{class:'fb',style:{marginBottom:'5px'}},el('div',{style:{display:'flex',alignItems:'center',gap:'8px'}},el('span',{style:{fontSize:'20px'}},ic),el('div',null,el('div',{style:{fontSize:'13px',fontWeight:'800'}},l),el('div',{style:{fontSize:'11px',color:'var(--tx2)'}},pct+'% of daily'))),el('div',{style:{textAlign:'right'}},el('div',{style:{fontSize:'19px',fontWeight:'900',color:c}},fmt(v)),el('div',{style:{fontSize:'10px',color:'var(--tx2)'}},'kcal'))));
    row.appendChild(el('div',{class:'pbar',style:{height:'4px',background:c+'20'}},el('div',{style:{height:'100%',width:pct+'%',background:c,borderRadius:'4px'}})));
    row.appendChild(el('div',{style:{fontSize:'11px',color:'var(--tx2)',marginTop:'6px'}},'💡 '+tip));sc.appendChild(row);
  });p.appendChild(sc);
  const tips=(RAM_TIPS[S.lang||'en']||RAM_TIPS.en);let tipIdx=0;const tipCard=el('div',{class:'card card-yl'});tipCard.appendChild(el('div',{class:'slbl'},__('fasting_tips')));const tipBody=el('div',{class:'tip tip-w',style:{minHeight:'46px',marginBottom:'9px'}});tipBody.textContent=tips[0];tipCard.appendChild(tipBody);const tnav=el('div',{class:'fb'});const pBtn=el('button',{class:'btn btn-gh btn-sm'},'← Prev');const nBtn=el('button',{class:'btn btn-gh btn-sm'},'Next →');const tCnt=el('span',{style:{fontSize:'12px',color:'var(--tx2)'}});tCnt.textContent='1/'+tips.length;pBtn.addEventListener('click',()=>{tipIdx=(tipIdx-1+tips.length)%tips.length;tipBody.textContent=tips[tipIdx];tCnt.textContent=(tipIdx+1)+'/'+tips.length;});nBtn.addEventListener('click',()=>{tipIdx=(tipIdx+1)%tips.length;tipBody.textContent=tips[tipIdx];tCnt.textContent=(tipIdx+1)+'/'+tips.length;});tnav.appendChild(pBtn);tnav.appendChild(tCnt);tnav.appendChild(nBtn);tipCard.appendChild(tnav);p.appendChild(tipCard);
  const rfc=el('div',{class:'card'});rfc.appendChild(el('div',{class:'slbl'},'🇲🇦 Recommended Ramadan Foods'));['h1','dt','kh','bg','eg','oa','yo','mt','z1','ls'].forEach(id=>{const f=FOODS.find(x=>x.id===id);if(!f)return;const fc=Math.round(f.cal*f.srv/100);rfc.appendChild(el('div',{class:'frow'},el('span',{class:'femo'},f.icon),el('div',{style:{flex:'1',minWidth:'0'}},el('div',{class:'fname'},f.name),el('div',{class:'fmeta'},f.ar+' — '+f.srv+'g')),el('div',{class:'fkcal'},fc+' kcal')));});p.appendChild(rfc);return p;
}
