// =========================================================
// PAGE: ACTIVITY
// =========================================================
function pgActiv(){
  const wKg=S.profile?S.profile.w:70;const p=el('div',{class:'page'});
  p.appendChild(el('div',{style:{marginBottom:'13px'}},el('span',{class:'badge bdg-pr',style:{marginBottom:'7px',display:'inline-flex'}},'ACTIVITY'),el('h1',{class:'h1'},__('activity'))));
  let selAct=null,mins=30;
  const ac=el('div',{class:'card'});ac.appendChild(el('div',{class:'slbl'},__('choose_act')));
  const ag=el('div',{style:{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'8px',marginBottom:'13px'}});
  ACTIVITIES.forEach(a=>{const sc=el('div',{class:'selc',style:{padding:'11px 12px',cursor:'pointer'}},el('span',{style:{fontSize:'20px'}},a.icon),el('div',{style:{fontSize:'12px',fontWeight:'700',flex:'1'}},a.name),el('div',{class:'sdot'}));sc.addEventListener('click',()=>{selAct=a;ag.querySelectorAll('.selc').forEach(x=>x.classList.remove('on'));sc.classList.add('on');const d2=sc.querySelector('.sdot');d2.style.background='var(--pr)';d2.style.borderColor='var(--pr)';updateRes();});ag.appendChild(sc);});
  ac.appendChild(ag);ac.appendChild(el('label',{class:'lbl'},__('dur_min')));
  const minp=el('input',{class:'inp',type:'number',value:'30',min:'1',max:'300',style:{marginBottom:'11px'}});minp.addEventListener('input',()=>{mins=parseFloat(minp.value)||30;updateRes();});
  const resD=el('div');resD.style.display='none';
  function updateRes(){if(!selAct)return;const burned=Math.round(selAct.met*wKg*(mins/60));resD.style.display='block';resD.innerHTML='';const rc=el('div',{class:'card card-pr glow-pr',style:{textAlign:'center',padding:'18px'}});rc.appendChild(el('div',{style:{fontSize:'12px',color:'var(--pr2)',fontWeight:'700',letterSpacing:'1px',textTransform:'uppercase',marginBottom:'5px'}},selAct.icon+' '+selAct.name));const dn=el('div',{class:'display',style:{fontSize:'50px'}});dn.textContent=fmt(burned);rc.appendChild(dn);rc.appendChild(el('div',{style:{fontSize:'12px',color:'var(--tx2)',marginTop:'4px',textTransform:'uppercase',letterSpacing:'1px'}},__('kcal_burned')));rc.appendChild(el('div',{style:{fontSize:'12px',color:'var(--tx2)',marginTop:'4px'}},mins+' min — '+wKg+'kg'));const sb=el('button',{class:'btn btn-pr btn-w',style:{marginTop:'11px'}},'💾 Log This Activity');sb.addEventListener('click',()=>{S.acts.push({id:Date.now(),actId:selAct.id,name:selAct.name,icon:selAct.icon,mins,burned,date:today()});saveS();checkAch();addXP(40,'Activity logged!');sb.textContent='✅ Saved!';sb.disabled=true;});resD.appendChild(rc);}
  ac.appendChild(minp);ac.appendChild(resD);p.appendChild(ac);
  const stc=el('div',{class:'card'});stc.appendChild(el('div',{class:'slbl'},__('steps_today')));
  if(S.steps.date!==today())S.steps={date:today(),count:0};
  const stepT=10000,stepP=Math.min(100,Math.round(S.steps.count/stepT*100)),sk=stpKcal(S.steps.count,wKg);
  stc.appendChild(el('div',{class:'fb',style:{marginBottom:'8px'}},el('div',null,el('div',{style:{fontSize:'30px',fontWeight:'900',color:'var(--or2)'}},S.steps.count.toLocaleString()),el('div',{style:{fontSize:'11px',color:'var(--tx2)'}},'/ '+stepT.toLocaleString()+' goal')),el('div',{style:{textAlign:'right'}},el('div',{style:{fontSize:'17px',fontWeight:'800',color:'var(--or2)'}},'-'+sk),el('div',{style:{fontSize:'10px',color:'var(--tx2)'}},'kcal burned'))));
  stc.appendChild(el('div',{class:'pbar',style:{height:'7px',marginBottom:'10px'}},el('div',{class:'pfil pf-or',style:{width:stepP+'%'}})));
  p.appendChild(el('div',{class:'tip tip-i',style:{marginBottom:'9px'}},'Steps formula: steps × weight(kg) × 0.0005. Example: 8,500 steps × 70kg = 298 kcal burned.'));
  const srow=el('div',{style:{display:'flex',gap:'8px'}});const sinp=el('input',{class:'inp',type:'number',placeholder:'Enter steps...',style:{flex:'1'}});const sbtn=el('button',{class:'btn btn-gh'},'Update');sbtn.addEventListener('click',()=>{const sv=parseInt(sinp.value);if(sv>0){S.steps.count=sv;saveS();render();}});srow.appendChild(sinp);srow.appendChild(sbtn);stc.appendChild(srow);p.appendChild(stc);
  const rec=[...S.acts].reverse().slice(0,8);
  if(rec.length>0){const hc=el('div',{class:'card'});hc.appendChild(el('div',{class:'slbl'},'Recent Activities'));const wb=S.acts.filter(a=>dago(a.date)<=7).reduce((s,a)=>s+a.burned,0);if(wb>0)hc.appendChild(el('div',{class:'card card-pr',style:{textAlign:'center',padding:'11px',marginBottom:'8px'}},el('div',{style:{fontSize:'22px',fontWeight:'900',color:'var(--pr2)'}},fmt(wb)),el('div',{style:{fontSize:'10px',color:'var(--tx2)',textTransform:'uppercase',letterSpacing:'1px'}},'Calories Burned This Week')));rec.forEach(a=>{const row=el('div',{style:{display:'flex',alignItems:'center',gap:'8px',padding:'8px 11px',background:'var(--glass2)',borderRadius:'11px',marginBottom:'6px'}},el('span',{style:{fontSize:'20px'}},a.icon),el('div',{style:{flex:'1'}},el('div',{style:{fontSize:'12px',fontWeight:'700'}},a.name),el('div',{style:{fontSize:'11px',color:'var(--tx2)',marginTop:'2px'}},a.mins+' min — '+a.date)),el('div',{style:{textAlign:'right'}},el('div',{style:{fontSize:'14px',fontWeight:'800',color:'var(--pr2)'}},'-'+a.burned),el('div',{style:{fontSize:'10px',color:'var(--tx2)'}},'kcal')));const db=el('button',{style:{background:'none',border:'none',color:'var(--tx2)',cursor:'pointer',fontSize:'17px',padding:'0 3px'}});db.textContent='×';db.addEventListener('click',()=>{S.acts=S.acts.filter(x=>x.id!==a.id);saveS();render();});row.appendChild(db);hc.appendChild(row);});p.appendChild(hc);}
  return p;
}
