// =========================================================
// PAGE: SLEEP
// =========================================================
function pgSleep(){
  const p=el('div',{class:'page'});p.appendChild(el('div',{style:{marginBottom:'13px'}},el('span',{class:'badge bdg-pu',style:{marginBottom:'7px',display:'inline-flex'}},'SLEEP'),el('h1',{class:'h1'},__('sleep')+' Tracker')));
  const sc=el('div',{class:'card'});sc.appendChild(el('div',{class:'slbl'},__('log_sleep')));let sh=7;
  const nc=el('div',{class:'nctrl',style:{justifyContent:'center',margin:'10px 0 13px'}});
  const mb=el('button',{class:'nbtn'},'−');const vd=el('div',{class:'nval',style:{color:'var(--pu2)'}},sh+'h');const pb=el('button',{class:'nbtn'},'+');
  const uq=()=>{vd.textContent=sh+'h';};mb.addEventListener('click',()=>{sh=Math.max(0,sh-0.5);uq();});pb.addEventListener('click',()=>{sh=Math.min(24,sh+0.5);uq();});
  nc.appendChild(mb);nc.appendChild(vd);nc.appendChild(pb);sc.appendChild(nc);
  const qual=el('div',{style:{textAlign:'center',marginBottom:'12px',fontSize:'13px',fontWeight:'600'}});
  const uqual=()=>{const q=sh>=9?['😴 Excellent!','var(--pr2)']:sh>=7?['✅ Good','var(--pr2)']:sh>=6?['⚠️ Fair','var(--yl2)']:sh>=4?['😟 Poor','var(--rd2)']:['🔴 Very Poor','var(--rd2)'];qual.textContent=q[0];qual.style.color=q[1];};
  mb.addEventListener('click',uqual);pb.addEventListener('click',uqual);uqual();sc.appendChild(qual);
  const sv=el('button',{class:'btn btn-pu btn-w'},__('log_sleep'));sv.addEventListener('click',()=>{S.sleep.push({id:Date.now(),date:today(),h:sh});if(S.sleep.length>90)S.sleep=S.sleep.slice(-90);saveS();addXP(20,'Sleep logged!');render();});sc.appendChild(sv);p.appendChild(sc);
  if(S.sleep.length>0){const avg7=S.sleep.slice(-7).reduce((s,x)=>s+x.h,0)/Math.min(7,S.sleep.length);const last=S.sleep[S.sleep.length-1];const sg=el('div',{class:'g3',style:{marginBottom:'13px'}});[[last.h+'h','Last night','var(--pu2)'],[avg7.toFixed(1)+'h','7-day avg',avg7>=7?'var(--pr2)':'var(--rd2)'],[String(S.sleep.length),'Entries','var(--ac2)']].forEach(([v,l,c])=>sg.appendChild(el('div',{class:'sbox'},el('div',{class:'sv',style:{color:c,fontSize:'17px'}},v),el('div',{class:'sl'},l))));p.appendChild(sg);
  if(avg7<7)p.appendChild(el('div',{class:'tip tip-w'},'Average sleep '+avg7.toFixed(1)+'h — below 7-9h optimal. Poor sleep increases ghrelin (hunger hormone) by 24%.'));
  if(S.sleep.length>2){const slc=el('div',{class:'card'});slc.appendChild(el('div',{class:'slbl'},'Sleep History'));const cv=el('canvas',{'aria-label':'Sleep history chart'});const cw=el('div',{class:'chwsm'});cw.appendChild(cv);slc.appendChild(cw);p.appendChild(slc);setTimeout(()=>{try{if(typeof Chart==='undefined')return;const th=typeof chartTheme==='function'?chartTheme():{grid:'rgba(255,255,255,.05)',tick:'#7a9abb',target:'#60a5fa'};const sl14=S.sleep.slice(-14);const ch=new Chart(cv,{type:'bar',data:{labels:sl14.map(x=>x.date.slice(5)),datasets:[{label:'Hours',data:sl14.map(x=>x.h),backgroundColor:sl14.map(x=>x.h>=7?'rgba(16,185,129,.6)':'rgba(239,68,68,.6)'),borderRadius:5,borderSkipped:false},{label:'Goal',data:Array(sl14.length).fill(7),type:'line',borderColor:th.target,borderDash:[5,4],pointRadius:0}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{min:0,max:12,grid:{color:th.grid},ticks:{color:th.tick,font:{size:10}}},x:{grid:{display:false},ticks:{color:th.tick,font:{size:10}}}}}});if(typeof registerChart==='function')registerChart(ch);}catch(e){}},80);}
  }const tc=el('div',{class:'card'});tc.appendChild(el('div',{class:'slbl'},'😴 Sleep Science'));['7-9 hours is optimal for fat loss — sleep regulates hunger hormones directly.','Avoid screens 1 hour before bed — blue light blocks melatonin by up to 50%.','Keep bedroom cool (18-20°C) for deeper, more restorative sleep stages.','No caffeine after 2 PM — it has a 6-hour half-life in your body.'].forEach(t=>tc.appendChild(el('div',{class:'tip tip-i',style:{marginBottom:'6px'}},t)));p.appendChild(tc);return p;
}
