// =========================================================
// PAGE: TRACK (Weight Log)
// =========================================================
function pgTrack(){
  if(!S.plan)return noProfCard();
  const pr=S.profile;const p=el('div',{class:'page'});
  p.appendChild(el('div',{style:{marginBottom:'13px'}},el('span',{class:'badge bdg-pr',style:{marginBottom:'7px',display:'inline-flex'}},'WEIGHT'),el('h1',{class:'h1'},'Weight Log')));
  const lc=el('div',{class:'card'});lc.appendChild(el('div',{class:'slbl'},__('log_weight')));
  const winp=el('input',{class:'inp',type:'number',step:'0.1',placeholder:pr.w.toFixed(1),style:{marginBottom:'8px'}});
  const ninp=el('input',{class:'inp',placeholder:__('note_opt'),style:{marginBottom:'11px'}});
  lc.appendChild(el('div',null,el('label',{class:'lbl'},__('weight_kg')),winp));lc.appendChild(el('div',null,el('label',{class:'lbl'},__('note_opt')),ninp));
  const ab=el('button',{class:'btn btn-pr btn-w',style:{marginTop:'2px'}},__('log_weight'));ab.addEventListener('click',()=>{const w=parseFloat(winp.value);if(!w||isNaN(w))return;const _le={id:Date.now(),date:today(),w,note:ninp.value||''};S.logs.push(_le);saveS();checkAch();dbSaveLog(_le);const td=today();if(S.streak.last!==td){const g=dago(S.streak.last||td);S.streak.count=g<=1?S.streak.count+1:1;S.streak.last=td;saveS();}addXP(25,'Weight logged!');winp.value='';ninp.value='';render();});lc.appendChild(ab);p.appendChild(lc);
  if(S.logs.length>0){const lat=S.logs[S.logs.length-1];const la=Math.max(0,pr.w-lat.w);const sg=el('div',{class:'g3',style:{marginBottom:'13px'}});[[lat.w+'kg',__('current'),'var(--pr2)'],['-'+la.toFixed(1)+'kg',__('lost'),la>0?'var(--pr2)':'var(--tx3)'],[String(S.logs.length),'Entries','var(--ac2)']].forEach(([v,l,c])=>sg.appendChild(el('div',{class:'sbox'},el('div',{class:'sv',style:{color:c,fontSize:'17px'}},v),el('div',{class:'sl'},l))));p.appendChild(sg);}
  if(S.logs.length>1){const wc=el('div',{class:'card'});wc.appendChild(el('div',{class:'slbl'},__('weight_trend')));const cv=el('canvas',{'aria-label':'Weight trend chart'});const cw=el('div',{class:'chw'});cw.appendChild(cv);wc.appendChild(cw);p.appendChild(wc);setTimeout(()=>{try{if(typeof Chart==='undefined')return;const th=typeof chartTheme==='function'?chartTheme():{grid:'rgba(255,255,255,.05)',tick:'#7a9abb',line:'#10b981',fill:'rgba(16,185,129,.1)',target:'#60a5fa'};const ls=S.logs.slice(-20).map(l=>l.date.slice(5));const dt=S.logs.slice(-20).map(l=>l.w);const ch=new Chart(cv,{type:'line',data:{labels:ls,datasets:[{label:'Weight',data:dt,borderColor:th.line,backgroundColor:th.fill,tension:.4,fill:true,pointBackgroundColor:th.line,pointRadius:4,pointHoverRadius:8},{label:'Target',data:Array(ls.length).fill(pr.t),borderColor:th.target,borderDash:[6,4],pointRadius:0,borderWidth:1.5}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{color:th.tick,font:{size:10},usePointStyle:true}}},scales:{y:{grid:{color:th.grid},ticks:{color:th.tick,font:{size:10}}},x:{grid:{display:false},ticks:{color:th.tick,font:{size:10}}}}}});if(typeof registerChart==='function')registerChart(ch);}catch(e){}},80);}
  if(S.logs.length>0){const hc=el('div',{class:'card'});let showAll=false;const hB=el('div');const hdr=el('div',{class:'fb',style:{marginBottom:'0'}});hdr.appendChild(el('div',{class:'slbl',style:{marginBottom:'0'}},__('history')+' ('+S.logs.length+')'));const tB=el('button',{class:'btn btn-gh btn-sm'},__('show_all'));tB.addEventListener('click',()=>{showAll=!showAll;tB.textContent=showAll?__('hide'):__('show_all');renderH();});function renderH(){hB.innerHTML='';const list=showAll?[...S.logs].reverse():[...S.logs].reverse().slice(0,7);list.forEach((l,i)=>{const prev=S.logs[S.logs.length-2-i];const diff=prev?+(l.w-prev.w).toFixed(1):null;const row=el('div',{style:{display:'flex',alignItems:'center',gap:'9px',padding:'8px 0',borderBottom:'1px solid var(--bor)'}},el('div',{style:{minWidth:'68px',fontSize:'11px',color:'var(--tx2)'}},l.date),el('div',{style:{fontSize:'14px',fontWeight:'800',flex:'1'}},l.w+' kg'),diff!==null?el('div',{style:{fontSize:'11px',fontWeight:'700',color:diff<0?'var(--pr2)':'var(--rd2)'}},(diff<0?'▼ ':'▲ ')+Math.abs(diff)):null,l.note?el('div',{style:{fontSize:'11px',color:'var(--tx2)',fontStyle:'italic',flex:'1',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}},l.note):null);const db=el('button',{style:{background:'none',border:'none',color:'var(--tx2)',cursor:'pointer',fontSize:'18px',padding:'0 3px',marginLeft:'auto'}});db.textContent='×';db.addEventListener('click',()=>{dbDeleteLog(l.id);S.logs=S.logs.filter(x=>x.id!==l.id);saveS();render();});row.appendChild(db);hB.appendChild(row);});}renderH();hdr.appendChild(tB);hc.appendChild(hdr);hc.appendChild(hB);p.appendChild(hc);}else p.appendChild(emptyState('📋',__('no_entries'),'Log your weight daily for trend insights.'));
  return p;
}
